export const REQUEST_LOGIN_ACTION = 'REQUEST_LOGIN_ACTION';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_ERROR_ACTION = 'LOGIN_ERROR_ACTION';
export const REQUEST_LOGOUT_ACTION = 'REQUEST_LOGOUT_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const CLEAR_LOGIN_ERRORS_ACTION = 'CLEAR_LOGIN_ERRORS_ACTION';
export const AUTH_STOP_FETCHING_ACTION = 'AUTH_STOP_FETCHING_ACTION';
